var number1 = 10;
var number2 = 5;
var result;
result = number1 + number2;
console.log(result);
result = number1 - number2;
console.log(result);
result = number1 * number2;
console.log(result);
result = number1 / number2;
console.log(result);
